### ISSUE TITLE
[DOCU]: Deploy v2 API documentation to github pages

### ISSUE THREAD

**Issue by CubicrootXYZ** [CubicrootXYZ/RemindMe#217]
### Describe your improvement

Deploy the currently uploaded artifact as github pages

### What part does your request relates to?

API documentation

### Where do you expect this information to be?

Unsure

### Checklist

- [X] I was not able to finde the proposed information in the [README](https://github.com/CubicrootXYZ/RemindMe), [API docu](https://cubicrootxyz.github.io/RemindMe/) and [Wiki](https://github.com/CubicrootXYZ/RemindMe/wiki)
- [X] I confirmed that there is no other issue requesting the same improvements

**Comment by kanz-1805** [comment]
Hi @CubicrootXYZ  I was looking into your API documentation requirement. If it is REST API, I'd love to help you with the documentation. Thanks!

**Comment by CubicrootXYZ** [comment]
> Hi @CubicrootXYZ I was looking into your API documentation requirement. If it is REST API, I'd love to help you with the documentation. Thanks!

Thanks for offering your assistance, I really do appreciate it. The service offers a HTTP Restful API, it is already documented in the code itself. There is a [CI job](https://github.com/CubicrootXYZ/RemindMe/blob/main/.github/workflows/main.yml#L53) that builds an OpenAPI specification file from it and renders it into a nice looking HTML page. 

The task for this issue is to get the deployment of this HTML file working. I already added another [CI job](https://github.com/CubicrootXYZ/RemindMe/blob/main/.github/workflows/main.yml#L84) for this but it does not work. If you want to tackle this I recommend looking into the [error message this job produced](https://github.com/CubicrootXYZ/RemindMe/actions/runs/8929294969/job/24564954193).

**Comment by CubicrootXYZ** [comment]
API documentation is now deployed to https://cubicrootxyz.github.io/RemindMe/index.html/
