### ISSUE TITLE
Allow import/sync of external calendars

### ISSUE THREAD

**Issue by keunes** [CubicrootXYZ/RemindMe#70]
Hello!
For the AntennaPod project we have a matrix channel/room for core contributors. We also have a calendar with events (ICS file accessible via URL, so read-only). I would love to set up a system that publishes reminders in our room for the events in that calendar. Is that something that's already possible? If  yes, how could we point the bot to this calendar? If not, please consider this a feature request.

Thanks!

**Comment by CubicrootXYZ** [comment]
Hey, thanks for your contribution. Currently the bot can not import/sync other calendars. It is designed to be a personal (or for a small team) tool that handles reminders. Those reminders can be exported as ical. 

I value your idea and will keep this open so we can have this feature some time on the future.

**Comment by CubicrootXYZ** [comment]
@keunes you can now add third party resources (ical links) via the api to a channel. Checkout the beta release for that feature. 

Currently this is not working for recurring and full-day events.

**Comment by keunes** [comment]
Nice, many thanks! I will have to experiment with the docker beta channel.

(Our most important meeting is our recurring monthly community meeting so support for that would be awesome too. But if I've set things up I can start already with the one-off reminders.)

What if you import the same iCal twice? Would it recognise the unique meeting ID (and avoid creating 2 reminders)?

**Comment by CubicrootXYZ** [comment]
> so support for that would be awesome too

I will work on that, tough can not promise anything currently. 

> What if you import the same iCal twice?

The unique ID is checked, so there won't be duplicate entries. Also remindme will check every 30 minutes for changes and will update the data if there are any changes.

**Comment by keunes** [comment]
Awesome! Thanks a lot 🙏

**Comment by CubicrootXYZ** [comment]
Recurring and full day events are now correctly parsed. @keunes feel free to give me some feedback how it runs and if there is anything to improve.
